### ISSUE TITLE
[Bug]: experimental load textual-inversion error

### ISSUE THREAD

**Issue by gaowanliang** [VoltaML/voltaML-fast-stable-diffusion#159] opened 2023-10-16 08:53 UTC
### Describe the bug

Using the experimental branch results in the following error, whereas using the main branch is fine.

use text-inversion: https://huggingface.co/embed/negative

### Reproduction

load text-inversion

### Expected behavior

loaded

### Installation Method

Local

### Branch

Experimental

### System Info

Linux

### Logs

```bash
INFO     08:46:29 | core.gpu » Loading textual inversion model: data/textual-inversion/bad-artist.pt                                                                       gpu.py:603
INFO     08:46:29 | core.inference.pytorch.pytorch » Loading textual inversion model data/textual-inversion/bad-artist.pt onto absolutereality_v181.safetensors...     pytorch.py:632
INFO     08:46:29 | core.inference.pytorch.pytorch » Loading token bad-artist for textual inversion model                                                              pytorch.py:653
INFO     08:46:29 | uvicorn.access » 240e:446:49:2a80:cde8:b3a4:c98f:5c03:0 - "POST /api/models/load-textual-inversion HTTP/1.1" 500                                  h11_impl.py:498
ERROR    08:46:29 | uvicorn.error » Exception in ASGI application                                                                                                     h11_impl.py:433
                                                                                                                                                                                     
         ╭─────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────╮                
         │ /.../venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py:428 in run_asgi                                           │                
         │                                                                                                                                                          │                
         │   425 │   # ASGI exception wrapper                                                                                                                       │                
         │   426 │   async def run_asgi(self, app: "ASGI3Application") -> None:                                                                                     │                
         │   427 │   │   try:                                                                                                                                       │                
         │ ❱ 428 │   │   │   result = await app(  # type: ignore[func-returns-value]                                                                                │                
         │   429 │   │   │   │   self.scope, self.receive, self.send                                                                                                │                
         │   430 │   │   │   )                                                                                                                                      │                
         │   431 │   │   except BaseException as exc:                                                                                                               │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py:78 in __call__                                           │                
         │                                                                                                                                                          │                
         │   75 │   │   │   │   │   port = 0                                                                                                                        │                
         │   76 │   │   │   │   │   scope["client"] = (host, port)  # type: ignore[arg-type]                                                                        │                
         │   77 │   │                                                                                                                                               │                
         │ ❱ 78 │   │   return await self.app(scope, receive, send)                                                                                                 │                
         │   79                                                                                                                                                     │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/fastapi/applications.py:276 in __call__                                                      │                
         │                                                                                                                                                          │                
         │   273 │   async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:                                                                  │                
         │   274 │   │   if self.root_path:                                                                                                                         │                
         │   275 │   │   │   scope["root_path"] = self.root_path                                                                                                    │                
         │ ❱ 276 │   │   await super().__call__(scope, receive, send)                                                                                               │                
         │   277 │                                                                                                                                                  │                
         │   278 │   def add_api_route(                                                                                                                             │                
         │   279 │   │   self,                                                                                                                                      │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/applications.py:122 in __call__                                                    │                
         │                                                                                                                                                          │                
         │   119 │   │   scope["app"] = self                                                                                                                        │                
         │   120 │   │   if self.middleware_stack is None:                                                                                                          │                
         │   121 │   │   │   self.middleware_stack = self.build_middleware_stack()                                                                                  │                
         │ ❱ 122 │   │   await self.middleware_stack(scope, receive, send)                                                                                          │                
         │   123 │                                                                                                                                                  │                
         │   124 │   def on_event(self, event_type: str) -> typing.Callable:  # pragma: nocover                                                                     │                
         │   125 │   │   return self.router.on_event(event_type)                                                                                                    │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/middleware/errors.py:184 in __call__                                               │                
         │                                                                                                                                                          │                
         │   181 │   │   │   # We always continue to raise the exception.                                                                                           │                
         │   182 │   │   │   # This allows servers to log the error, or allows test clients                                                                         │                
         │   183 │   │   │   # to optionally raise the error within the test case.                                                                                  │                
         │ ❱ 184 │   │   │   raise exc                                                                                                                              │                
         │   185 │                                                                                                                                                  │                
         │   186 │   def format_line(                                                                                                                               │                
         │   187 │   │   self, index: int, line: str, frame_lineno: int, frame_index: int                                                                           │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/middleware/errors.py:162 in __call__                                               │                
         │                                                                                                                                                          │                
         │   159 │   │   │   await send(message)                                                                                                                    │                
         │   160 │   │                                                                                                                                              │                
         │   161 │   │   try:                                                                                                                                       │                
         │ ❱ 162 │   │   │   await self.app(scope, receive, _send)                                                                                                  │                
         │   163 │   │   except Exception as exc:                                                                                                                   │                
         │   164 │   │   │   request = Request(scope)                                                                                                               │                
         │   165 │   │   │   if self.debug:                                                                                                                         │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/middleware/cors.py:92 in __call__                                                  │                
         │                                                                                                                                                          │                
         │    89 │   │   │   await response(scope, receive, send)                                                                                                   │                
         │    90 │   │   │   return                                                                                                                                 │                
         │    91 │   │                                                                                                                                              │                
         │ ❱  92 │   │   await self.simple_response(scope, receive, send, request_headers=headers)                                                                  │                
         │    93 │                                                                                                                                                  │                
         │    94 │   def is_allowed_origin(self, origin: str) -> bool:                                                                                              │                
         │    95 │   │   if self.allow_all_origins:                                                                                                                 │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/middleware/cors.py:147 in simple_response                                          │                
         │                                                                                                                                                          │                
         │   144 │   │   self, scope: Scope, receive: Receive, send: Send, request_headers: Headers                                                                 │                
         │   145 │   ) -> None:                                                                                                                                     │                
         │   146 │   │   send = functools.partial(self.send, send=send, request_headers=request_headers)                                                            │                
         │ ❱ 147 │   │   await self.app(scope, receive, send)                                                                                                       │                
         │   148 │                                                                                                                                                  │                
         │   149 │   async def send(                                                                                                                                │                
         │   150 │   │   self, message: Message, send: Send, request_headers: Headers                                                                               │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py:79 in __call__                                            │                
         │                                                                                                                                                          │                
         │    76 │   │   │   │   handler = self._lookup_exception_handler(exc)                                                                                      │                
         │    77 │   │   │                                                                                                                                          │                
         │    78 │   │   │   if handler is None:                                                                                                                    │                
         │ ❱  79 │   │   │   │   raise exc                                                                                                                          │                
         │    80 │   │   │                                                                                                                                          │                
         │    81 │   │   │   if response_started:                                                                                                                   │                
         │    82 │   │   │   │   msg = "Caught handled exception, but response already started."                                                                    │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py:68 in __call__                                            │                
         │                                                                                                                                                          │                
         │    65 │   │   │   await send(message)                                                                                                                    │                
         │    66 │   │                                                                                                                                              │                
         │    67 │   │   try:                                                                                                                                       │                
         │ ❱  68 │   │   │   await self.app(scope, receive, sender)                                                                                                 │                
         │    69 │   │   except Exception as exc:                                                                                                                   │                
         │    70 │   │   │   handler = None                                                                                                                         │                
         │    71                                                                                                                                                    │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py:21 in __call__                                          │                
         │                                                                                                                                                          │                
         │   18 │   │   │   │   │   await self.app(scope, receive, send)                                                                                            │                
         │   19 │   │   │   │   except Exception as e:                                                                                                              │                
         │   20 │   │   │   │   │   dependency_exception = e                                                                                                        │                
         │ ❱ 21 │   │   │   │   │   raise e                                                                                                                         │                
         │   22 │   │   │   if dependency_exception:                                                                                                                │                
         │   23 │   │   │   │   # This exception was possibly handled by the dependency but it should                                                               │                
         │   24 │   │   │   │   # still bubble up so that the ServerErrorMiddleware can return a 500                                                                │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py:18 in __call__                                          │                
         │                                                                                                                                                          │                
         │   15 │   │   │   async with AsyncExitStack() as stack:                                                                                                   │                
         │   16 │   │   │   │   scope[self.context_name] = stack                                                                                                    │                
         │   17 │   │   │   │   try:                                                                                                                                │                
         │ ❱ 18 │   │   │   │   │   await self.app(scope, receive, send)                                                                                            │                
         │   19 │   │   │   │   except Exception as e:                                                                                                              │                
         │   20 │   │   │   │   │   dependency_exception = e                                                                                                        │                
         │   21 │   │   │   │   │   raise e                                                                                                                         │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/routing.py:718 in __call__                                                         │                
         │                                                                                                                                                          │                
         │   715 │   │   │   match, child_scope = route.matches(scope)                                                                                              │                
         │   716 │   │   │   if match == Match.FULL:                                                                                                                │                
         │   717 │   │   │   │   scope.update(child_scope)                                                                                                          │                
         │ ❱ 718 │   │   │   │   await route.handle(scope, receive, send)                                                                                           │                
         │   719 │   │   │   │   return                                                                                                                             │                
         │   720 │   │   │   elif match == Match.PARTIAL and partial is None:                                                                                       │                
         │   721 │   │   │   │   partial = route                                                                                                                    │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/routing.py:276 in handle                                                           │                
         │                                                                                                                                                          │                
         │   273 │   │   │   │   )                                                                                                                                  │                
         │   274 │   │   │   await response(scope, receive, send)                                                                                                   │                
         │   275 │   │   else:                                                                                                                                      │                
         │ ❱ 276 │   │   │   await self.app(scope, receive, send)                                                                                                   │                
         │   277 │                                                                                                                                                  │                
         │   278 │   def __eq__(self, other: typing.Any) -> bool:                                                                                                   │                
         │   279 │   │   return (                                                                                                                                   │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/starlette/routing.py:66 in app                                                               │                
         │                                                                                                                                                          │                
         │    63 │   async def app(scope: Scope, receive: Receive, send: Send) -> None:                                                                             │                
         │    64 │   │   request = Request(scope, receive=receive, send=send)                                                                                       │                
         │    65 │   │   if is_coroutine:                                                                                                                           │                
         │ ❱  66 │   │   │   response = await func(request)                                                                                                         │                
         │    67 │   │   else:                                                                                                                                      │                
         │    68 │   │   │   response = await run_in_threadpool(func, request)                                                                                      │                
         │    69 │   │   await response(scope, receive, send)                                                                                                       │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/fastapi/routing.py:237 in app                                                                │                
         │                                                                                                                                                          │                
         │    234 │   │   if errors:                                                                                                                                │                
         │    235 │   │   │   raise RequestValidationError(errors, body=body)                                                                                       │                
         │    236 │   │   else:                                                                                                                                     │                
         │ ❱  237 │   │   │   raw_response = await run_endpoint_function(                                                                                           │                
         │    238 │   │   │   │   dependant=dependant, values=values, is_coroutine=is_coroutine                                                                     │                
         │    239 │   │   │   )                                                                                                                                     │                
         │    240                                                                                                                                                   │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/fastapi/routing.py:163 in run_endpoint_function                                              │                
         │                                                                                                                                                          │                
         │    160 │   assert dependant.call is not None, "dependant.call must be a function"                                                                        │                
         │    161 │                                                                                                                                                 │                
         │    162 │   if is_coroutine:                                                                                                                              │                
         │ ❱  163 │   │   return await dependant.call(**values)                                                                                                     │                
         │    164 │   else:                                                                                                                                         │                
         │    165 │   │   return await run_in_threadpool(dependant.call, **values)                                                                                  │                
         │    166                                                                                                                                                   │                
         │                                                                                                                                                          │                
         │ /.../api/routes/models.py:142 in load_textual_inversion                                                                             │                
         │                                                                                                                                                          │                
         │   139 async def load_textual_inversion(req: TextualInversionLoadRequest):                                                                                │                
         │   140 │   "Load a LoRA model into a model"                                                                                                               │                
         │   141 │                                                                                                                                                  │                
         │ ❱ 142 │   await gpu.load_textual_inversion(req)                                                                                                          │                
         │   143 │   await websocket_manager.broadcast(data=Data(data_type="refresh_models", data={}))                                                              │                
         │   144 │   return {"message": "LoRA model loaded"}                                                                                                        │                
         │   145                                                                                                                                                    │                
         │                                                                                                                                                          │                
         │ /.../core/gpu.py:605 in load_textual_inversion                                                                                      │                
         │                                                                                                                                                          │                
         │   602 │   │   │   if isinstance(internal_model, PyTorchStableDiffusion):                                                                                 │                
         │   603 │   │   │   │   logger.info(f"Loading textual inversion model: {req.textual_inversion}")                                                           │                
         │   604 │   │   │   │                                                                                                                                      │                
         │ ❱ 605 │   │   │   │   internal_model.load_textual_inversion(req.textual_inversion)                                                                       │                
         │   606 │   │   │   │                                                                                                                                      │                
         │   607 │   │   │   │   websocket_manager.broadcast_sync(                                                                                                  │                
         │   608 │   │   │   │   │   Notification(                                                                                                                  │                
         │                                                                                                                                                          │                
         │ /.../core/inference/pytorch/pytorch.py:655 in load_textual_inversion                                                                │                
         │                                                                                                                                                          │                
         │   652 │   │   token = Path(textual_inversion).stem                                                                                                       │                
         │   653 │   │   logger.info(f"Loading token {token} for textual inversion model")                                                                          │                
         │   654 │   │                                                                                                                                              │                
         │ ❱ 655 │   │   pipe.load_textual_inversion(textual_inversion, token=token)                                                                                │                
         │   656 │   │                                                                                                                                              │                
         │   657 │   │   self.textual_inversions.append(textual_inversion)                                                                                          │                
         │   658 │   │   logger.info(f"Textual inversion model {textual_inversion} loaded successfully")                                                            │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/diffusers/loaders.py:1002 in load_textual_inversion                                          │                
         │                                                                                                                                                          │                
         │    999 │   │   self._check_text_inv_inputs(tokenizer, text_encoder,                                                                                      │                
         │        pretrained_model_name_or_paths, tokens)                                                                                                           │                
         │   1000 │   │                                                                                                                                             │                
         │   1001 │   │   # 4. Load state dicts of textual embeddings                                                                                               │                
         │ ❱ 1002 │   │   state_dicts = load_textual_inversion_state_dicts(pretrained_model_name_or_paths,                                                          │                
         │        **kwargs)                                                                                                                                         │                
         │   1003 │   │                                                                                                                                             │                
         │   1004 │   │   # 4. Retrieve tokens and embeddings                                                                                                       │                
         │   1005 │   │   tokens, embeddings = self._retrieve_tokens_and_embeddings(tokens, state_dicts,                                                            │                
         │        tokenizer)                                                                                                                                        │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/diffusers/loaders.py:719 in load_textual_inversion_state_dicts                               │                
         │                                                                                                                                                          │                
         │    716 │   │   │   │   │   subfolder=subfolder,                                                                                                          │                
         │    717 │   │   │   │   │   user_agent=user_agent,                                                                                                        │                
         │    718 │   │   │   │   )                                                                                                                                 │                
         │ ❱  719 │   │   │   │   state_dict = torch.load(model_file, map_location="cpu")                                                                           │                
         │    720 │   │   else:                                                                                                                                     │                
         │    721 │   │   │   state_dict = pretrained_model_name_or_path                                                                                            │                
         │    722                                                                                                                                                   │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/torch/serialization.py:815 in load                                                           │                
         │                                                                                                                                                          │                
         │    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,                                                           │                
         │        **pickle_load_args)                                                                                                                               │                
         │    813 │   │   │   except RuntimeError as e:                                                                                                             │                
         │    814 │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None                                                                   │                
         │ ❱  815 │   │   return _legacy_load(opened_file, map_location, pickle_module,                                                                             │                
         │        **pickle_load_args)                                                                                                                               │                
         │    816                                                                                                                                                   │                
         │    817                                                                                                                                                   │                
         │    818 # Register pickling support for layout instances such as                                                                                          │                
         │                                                                                                                                                          │                
         │ /.../venv/lib/python3.10/site-packages/torch/serialization.py:1033 in _legacy_load                                                  │                
         │                                                                                                                                                          │                
         │   1030 │   │   │   f"Received object of type \"{type(f)}\". Please update to Python 3.8.2 or                                                             │                
         │        newer to restore this "                                                                                                                           │                
         │   1031 │   │   │   "functionality.")                                                                                                                     │                
         │   1032 │                                                                                                                                                 │                
         │ ❱ 1033 │   magic_number = pickle_module.load(f, **pickle_load_args)                                                                                      │                
         │   1034 │   if magic_number != MAGIC_NUMBER:                                                                                                              │                
         │   1035 │   │   raise RuntimeError("Invalid magic number; corrupt file?")                                                                                 │                
         │   1036 │   protocol_version = pickle_module.load(f, **pickle_load_args)                                                                                  │                
         ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                
         UnpicklingError: invalid load key, 'v'.
```
```


### Additional context

_No response_

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment] 2023-10-17 20:04
Tested EasyNegativeV2 from that repo, dunno who uploaded it but it is borked/potentially malicious. 

Download official stuff from CivitAI website - here is a link to correct weights for ENV2: https://civitai.com/models/100191/ti-easynegativev2-textual-inversion-embedding

Closing as the issue is not on our side.

**Closed by Stax124** 2023-10-17 20:04 UTC
Labels: Question
